# Generated by Django 5.2.11 on 2026-02-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.course'),
        ),
    ]
